config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.find(params[:id])
    @flat = Flat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_controller_helper.rb
module FlatsControllerHelper
end

app/views/flats/index.html.erb
<h1>Simple Airbnb</h1>

<h2>All our Flats</h2>

<p>You searched for. We found 3 flats of our 3 in our website</p>


<div class="row">
  <div class="col-4">
    <img class="card-img-top" src="house1.jpg" alt="Card image cap">
      <div class="flat-card-content">
        <% @flats.each do |flat| %>

          <div class="card-body">
          <h5 class="card-title">flat.name</h5>
          <%= link_to flat.name, flat_path(flat) %>
          <%= flat.description%>
          <%= flat.price_per_night%>
          <%= flat.number_of_guests %>

          <%= link_to '<i class="fas fa-trash"></i>'.html_safe, flat_path(flat.id), method: :delete, data: { confirm: "Are you sure?" }%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAirbnb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %>
  <%= javascript_tag "application" %>
</body>
</body>
</html>